### PR TITLE
Siren Authorisation

### PR DESCRIPTION
**Pull request by NorfairKing**

### CODE REVIEW

**Comment by NorfairKing** [comment]
This is for #13.

**Comment by NorfairKing** [comment]
Things that still need to be done: Separate 'copy' from 'create' and make authorisation for that.

**Comment by achirkin** [comment]
I've fixes some minor things and implemented copy scenario; check out my siren-authorisation branch. Now, it really needs some testing :)

**Comment by achirkin** [comment]
This seems to be already imported

**Pull request closed without merging**
